url: /

pygments: true
paginate: 5

authors:
  josh:
    display_name: Joshua Minnie
    gravatar: 0d9ad0a17b1f1e22d38997ecc8269596
    email: me@joshuaminnie.com
    web: http://joshuaminnie.com/
    linkedin: joshua.minnie
    appnet: joshminnie
    twitter: joshminnie
    github: joshminnie
    bitbucket: joshminnie
    stackoverflow: 438275/josh
